---
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: yes
- name: Update all packages to the latest version
  apt:
    upgrade: dist
    force_apt_get: yes
- name: install backend packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - graphite-web
    - graphite-carbon
    - postgresql
    - apache2
    - libpq-dev
    - libapache2-mod-wsgi
    - python-psycopg2
    - python-dev
- name: Set up sample test metrics
  template:
    src: storage-schemas.conf
    dest: /etc/carbon/storage-schemas.conf
- name: Make a copy of default configuration file
  copy:
    src: /usr/share/doc/graphite-carbon/examples/storage-aggregation.conf.example
    dest: /usr/share/doc/graphite-carbon/examples/storage-aggregation.conf
    remote_src: yes
- name: Enable carbon to run on boot
  replace:
    path: /etc/default/graphite-carbon
    regexp: 'CARBON_CACHE_ENABLED=false'
    replace: 'CARBON_CACHE_ENABLED=true'
    backup: yes
  notify: Restart Carbon cache service
- name: Create Postgresql user and database
  become_user: postgres
  postgresql_user:
    name: graphite
    password: graphite
- name: Create graphite and grafana db
  become_user: postgres
  postgresql_db:
    name: "{{ item }}"
    owner: graphite
  loop:
    - graphite
    - grafana


