--- 
- name: install haproxy package
  package: name={{ item }} state=present
  with_items:
    - haproxy
  become: true

- name: set SELinux permissions for haproxy
  command: setsebool -P haproxy_connect_any 1
  become: true

- name: copy haproxy.cfg for vault
  copy:
    src="{{ role_path }}/files/haproxy.cfg"
    dest=/etc/haproxy/haproxy.cfg
    mode=644
    backup=yes
  become: true
  notify:
    - enable/restart haproxy

