# -*- mode: ruby -*-
# vi: set ft=ruby :

servers={
    "a-bootapp" => "192.168.33.36",
    "b-app" => "192.168.33.37",
    "c-app" => "192.168.33.38",
    "d-web" => "192.168.33.39",
}
Vagrant.configure(2) do |config|
    config.ssh.insert_key = false
    servers.each_with_index do |(hostname, ip), index|
        config.vm.define hostname do |node|
            config.vbguest.auto_update = false
            node.vm.box_check_update = false
            node.vm.box = "centos/7"
            node.vm.hostname = "#{hostname}.example.org"
            node.vm.network "private_network", ip: "#{ip}"
            node.vm.network "forwarded_port", guest: 80, host: "1808#{index}"
            node.vm.network "forwarded_port", guest: 8500, host: "1850#{index}"
            node.vm.network "forwarded_port", guest: 8200, host: "1820#{index}"
            node.vm.network "forwarded_port", guest: 1936, host: "1193#{index}"
            node.vm.synced_folder ".", "/vagrant"
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", 1024]
                vb.linked_clone = true if Vagrant::VERSION =~ /^1.8/
            end
            config.vm.provision "shell",  inline: <<-SHELL
              sudo systemctl restart rsyslog
            SHELL
            # https://www.vagrantup.com/docs/provisioning/ansible.html#ansible-parallel-execution
            if index == servers.size-1
                config.vm.provision "ansible" do |ansible|
                  ansible.limit = "all"
                  ansible.verbose = "v"
                  ansible.playbook = "consul_vault_haproxy.yml"
                  ansible.groups = {
                  "bootstrap_app_server" => servers.keys[0],
                  "app_server" => [servers.keys[1], servers.keys[2]],
                  "webserver" => servers.keys[3]
                  }
                end 
            end 
        end 
    end 
end 
