---
- name: install packages
  become: true
  package: name={{ item }} state=present
  with_items:
    - bind-utils
    - net-tools
    - unzip
    - dnsmasq
    - epel-release
    - telnet
    - wget
