---
- name: enable/restart consul
  service:
    name=consul
    state=restarted
    enabled=yes
  become: true

- name: enable/restart vault
  service:
    name=vault
    state=restarted
    enabled=yes
  become: true
