# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-vbguest")
  raise 'vagrant-vbguest plugin is not installed!'
end

$script = <<SCRIPT
  cp -R /home/vagrant/.ssh/ /root/
  cp -R /home/vagrant/.bashrc /root/.bashrc
  sed 's/PermitRootLogin yes/PermitRootLogin no/g;s/#PermitRootLogin/PermitRootLogin/g' /etc/ssh/sshd_config
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vbguest.auto_update = false
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.memory = "512"
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end
  config.vm.define "lb-0" do |c|
      c.vm.hostname = "lb-0"
      c.vm.network "private_network", ip: "192.168.199.40"
      c.vm.provider "virtualbox" do |vb|
        vb.memory = "256"
      end
  end
  (0..1).each do |n|
    config.vm.define "controller-#{n}" do |c|
        c.vm.hostname = "controller-#{n}"
        c.vm.network "private_network", ip: "192.168.199.1#{n}"
        c.vm.provider "virtualbox" do |vb|
          vb.memory = "640"
        end
    end
  end
  (0..1).each do |n|
    config.vm.define "worker-#{n}" do |c|
        c.vm.hostname = "worker-#{n}"
        c.vm.network "private_network", ip: "192.168.199.2#{n}"
    end
  end
end
