---
- name: Create /opt/certificates directory
  file: 
    path: "{{ item }}"
    mode: 0644
    state: directory
  loop:
  - '/opt/certificates'
  - '/opt/certificates/inputfiles'
- name: Copy input files for generating certificates
  copy:
    src: "{{ role_path }}/files/"
    dest: '/opt/certificates/inputfiles/'
- name: Generate CA
  shell: /usr/local/bin/cfssl gencert -initca "/opt/certificates/inputfiles/ca-csr.json" | /usr/local/bin/cfssljson -bare ca
  args:
    chdir: /opt/certificates