---
- name: Generate The kubelet Kubernetes Configuration File - Step 1
  shell: >
    /root/kubectl config set-cluster kubernetes-the-hard-way
    --certificate-authority=/opt/certificates/output/ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443 \
    --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /opt/kubeconfigs/output
- command: md5sum /opt/kubeconfigs/output/kube-controller-manager.kubeconfig
  register: md5out
- debug: var=md5out.stdout
- name: Generate The kubelet Kubernetes Configuration File - Step 2
  shell: >
    /root/kubectl config set-credentials system:kube-controller-manager
    --client-certificate=/opt/certificates/output/kube-controller-manager.pem \
    --client-key=/opt/certificates/output/kube-controller-manager-key.pem \
    --embed-certs=true \
    --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /opt/kubeconfigs/output
- command: md5sum /opt/kubeconfigs/output/kube-controller-manager.kubeconfig
  register: md5out
- debug: var=md5out.stdout
- name: Generate The kubelet Kubernetes Configuration File - Step 3
  shell: >
    /root/kubectl config set-context default
    --cluster=kubernetes-the-hard-way \
    --user=system:kube-controller-manager \
    --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /opt/kubeconfigs/output
- shell: md5sum /opt/kubeconfigs/output/kube-controller-manager.kubeconfig
  register: md5out
- debug: var=md5out.stdout
- name: Generate The kubelet Kubernetes Configuration File - Step 4
  shell: >
    /root/kubectl config use-context default
    --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /opt/kubeconfigs/output
- shell: md5sum /opt/kubeconfigs/output/kube-controller-manager.kubeconfig
  register: md5out
- debug: var=md5out.stdout
#- name: Generate The kube-proxy Kubernetes Configuration File
#- name: Generate The kube-controller-manager Kubernetes Configuration File
#- name: Generate The kube-scheduler Kubernetes Configuration File
#- name: Generate The admin Kubernetes Configuration File